# Generated by Django 4.0.3 on 2022-06-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministro',
            old_name='partido',
            new_name='cartera',
        ),
    ]
